### ISSUE TITLE
The solver hangs if I compile with threads and run it from python.

### ISSUE THREAD

**Issue by stschubert** [dongjing3309/minisam#8]
Is there anything new about the below reported issue? I'm asking since I have the same problem.

**Update:** Looks like the solver hangs if I compile with threads and run it from python. I removed the cmake flags above.

_Originally posted by @NikolausDemmel in https://github.com/dongjing3309/minisam/issues/7#issuecomment-570688234_

**Comment by stschubert** [comment]
By now, I could figure out that there is a problem in _minisam/python/minisam_wrapper/factor.cpp_ in _PYBIND11_OVERLOAD_PURE(Eigen::VectorXd, Factor, error, variables);_ (line 70). However, I don't know how pybind works...

**Comment by dongjing3309** [comment]
Hi @stschubert , my feeling is I must have a bug in multi-threading and causes deadlock. Do you have the example here which will helps me debug a lot? Thanks!

**Comment by NikolausDemmel** [comment]
I just came across [this discussion](https://groups.google.com/d/topic/ceres-solver/JG6lFsLqmP8/discussion) about python bindings and multi-threading, and thought that it might be related.

**Comment by Edwinem** [comment]
I was able to reproduce the issue with the _gps_factor_example.py_. I can also confirm that it has to do with the GIL. 

Running the code through a debugger it deadlocks currently on 
https://github.com/dongjing3309/minisam/blob/eda47f9795e5b0f04030e5bca1f94a6ce69d8292/minisam/core/FactorGraph.cpp#L83 

and

https://github.com/pybind/pybind11/blob/5b4751af269afab9a2e40a92b486bd29214f352b/include/pybind11/pybind11.h#L1911

~~It can be fixed by releasing the GIL before the thread joins. As seen below.~~

```cpp
  pybind11::gil_scoped_release release;
  // wait threads to finish
  for (int i = 0; i < MINISAM_WITH_MULTI_THREADS_NUM; i++) {
    linthreads[i].join();
  }
```

~~This has to be done in both **FactorGraph.cpp** and **linearization.cpp**.~~

~~Note this now creates a dependency on Python and Pybind11 in minisam. So you probably have to add some new compile time flags where if the python package is enabled then this line is added.~~

**Update:**

A better fix is provided in https://github.com/dongjing3309/minisam/pull/10. It is cleaner and does not require a Python dependency.

**Comment by dongjing3309** [comment]
should be fixed by PR1
